/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RATService;
import javax.xml.ws.Endpoint;

public class Provider {
    private static final String URL = "http://localhost:9000/rat";

    public static void main(String[] args) {

        RAT RATService = new RAT();
        System.out.println("Publishing RAT Service");
        Endpoint.publish(URL, RATService);
        System.out.println("RAT Service Published");
    }
}

// wsgen -wsdl -cp app/build/classes/java/main -d app/build/classes/java/main/ -r app/src/main/resources  RATService.RAT